# Generated by Django 3.2.11 on 2022-01-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='lecturer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
