# Generated by Django 3.2.11 on 2022-01-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.userprofile'),
        ),
        migrations.AlterField(
            model_name='participantcheckin',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.userprofile'),
        ),
    ]
