# Generated by Django 3.2.11 on 2022-01-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20220113_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytimeline',
            old_name='lecturer',
            new_name='lecturer_name',
        ),
    ]
