# Generated by Django 3.2.11 on 2022-01-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_rename_lecturer_activitytimeline_lecturer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='student_id',
            new_name='member_id',
        ),
    ]
