# Generated by Django 3.2.11 on 2022-01-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_rename_student_id_userprofile_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('activity', 'userprofile')},
        ),
    ]
