# Generated by Django 3.2.11 on 2022-01-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20220113_2338'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantcheckin',
            unique_together={('activity', 'userprofile')},
        ),
    ]
