# Generated by Django 3.2.11 on 2022-01-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_alter_participantcheckin_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantcheckin',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity'),
        ),
    ]
