# Generated by Django 3.2.11 on 2022-01-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_alter_participantcheckin_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytimeline',
            name='end_datetime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activitytimeline',
            name='start_datetime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
