# Generated by Django 3.2.11 on 2022-02-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20220115_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytimeline',
            name='timeline_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activitytimeline',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activitytimeline',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
