# Generated by Django 3.2.11 on 2022-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_auto_20220203_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytimeline',
            name='end_datetime_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activitytimeline',
            name='start_datetime_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
