# Generated by Django 3.2.11 on 2022-03-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_auto_20220322_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytimeline',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitytimeline',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
